# Generated by Django 5.1.4 on 2025-01-10 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_type', models.CharField(max_length=100)),
                ('w_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('w_brand', models.CharField(max_length=100)),
                ('w_model', models.CharField(max_length=100)),
                ('w_price', models.IntegerField()),
                ('w_features', models.TextField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
