# Generated by Django 5.1.4 on 2025-01-10 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_watchs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchs',
            old_name='watch_type',
            new_name='watchtype',
        ),
    ]
