# Generated by Django 5.1.4 on 2025-01-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pswd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
