# Generated by Django 5.1.4 on 2025-01-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_user_last_login_user_password_alter_user_pswd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AlterField(
            model_name='user',
            name='pswd',
            field=models.CharField(max_length=100),
        ),
    ]
